// demos/replay/3d/build.mjs
// ─────────────────────────────────────────────────────────────────
// Offline build for The Audit Room (Shadow M5 XR).
//
// Spec §Phase 7.4: "single static build, runs from file://, all assets
// vendored, zero network at runtime." Chrome blocks ES-module loading AND
// every fetch on file:// pages, so we bundle the WHOLE app — our modules +
// three + the shared verifier/tamper code + the inlined demo data — into ONE
// classic IIFE script (dist/audit-room.js) that index.html loads with a plain
// <script> tag. Double-clicking index.html then Just Works, no server, no
// flags, no network. This script is the ONLY build-time network step (it
// resolves three from node_modules); the running demo touches nothing off-disk.
//
//   demo-data.js         — real bundle + pubkey + beats, inlined (module,
//                          consumed by the bundler below)
//   dist/audit-room.js   — the single self-contained IIFE the page loads
//
// Run: node demos/replay/3d/build.mjs
// ─────────────────────────────────────────────────────────────────
import { build } from "esbuild";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "..", "..", "..");
mkdirSync(resolve(HERE, "dist"), { recursive: true });

const R = (...p) => resolve(REPO, ...p);

async function run() {
  // 1 — inline the real demo bundle + public key + presenter beats so
  // file:// needs no fetch (Chrome blocks all fetch on file:// pages).
  const bundle = readFileSync(R("demos", "replay", "data", "demo-session.bundle.json"), "utf8").trim();
  const pem = readFileSync(R("demos", "replay", "data", "demo-public-key.pem"), "utf8").trim();
  const beats = readFileSync(resolve(HERE, "demo-beats.json"), "utf8").trim();
  const dataModule =
`// demos/replay/3d/demo-data.js — GENERATED by build.mjs, do not hand-edit.
// The real sanitized Claude Code evidence bundle, its Ed25519 public key,
// and the presenter beats — inlined so The Audit Room runs from file:// with
// zero fetch. Regenerate with \`node demos/replay/3d/build.mjs\` after editing
// demo-session.bundle.json or demo-beats.json.
export const DEMO_BUNDLE = ${bundle};
export const DEMO_PUBLIC_KEY_PEM = ${JSON.stringify(pem)};
export const DEMO_BEATS = ${beats};
`;
  writeFileSync(resolve(HERE, "demo-data.js"), dataModule);

  // 2 — bundle the whole app into one classic IIFE the page loads directly.
  await build({
    entryPoints: [resolve(HERE, "app.js")],
    bundle: true, format: "iife", legalComments: "none",
    target: ["chrome110"], platform: "browser",
    outfile: resolve(HERE, "dist", "audit-room.js"),
  });

  console.log("[build] demo-data.js       (bundle + pubkey + beats inlined)");
  console.log("[build] dist/audit-room.js (single IIFE, three + app + verifier)");
  console.log("[build] done — double-click index.html; offline from file://");
}

run().catch((e) => { console.error(e); process.exit(1); });
