// <auto-generated> ShadowSpatialContract.g.cs — DO NOT EDIT.
// Generated from apps/shadow-lens/web/spatial-agent/{client-actions.mjs, src/app/types.ts}
// by scripts/gen-unity-contract.mjs. The Unity client shares ONE action/state/status schema
// with the tested web client; the drift test fails if this file is stale.
#if UNITY_2020_1_OR_NEWER
using System.Collections.Generic;
namespace ShadowLens.SpatialAgent {
  public static class ShadowSpatialContract {
    public static readonly string[] Actions = { "select_object", "focus_object", "highlight_source", "highlight_claim", "highlight_metric", "move_camera_to_object", "open_document_mode", "open_source_mode", "open_risk_mode", "open_review_mode", "open_audit_mode", "open_experiment_mode", "open_code_replay_mode", "show_tamper_diff", "show_verification_failure", "start_audit_walkthrough", "start_experiment_walkthrough", "start_code_walkthrough", "return_to_workspace", "clear_selection" };
    // action name -> required arg key (null = no arg)
    public static readonly Dictionary<string,string> ActionArg = new Dictionary<string,string> {
      { "select_object", "object_id" },
      { "focus_object", "object_id" },
      { "highlight_source", "source_id" },
      { "highlight_claim", "claim_id" },
      { "highlight_metric", "object_id" },
      { "move_camera_to_object", "object_id" },
      { "open_document_mode", null },
      { "open_source_mode", null },
      { "open_risk_mode", null },
      { "open_review_mode", null },
      { "open_audit_mode", null },
      { "open_experiment_mode", null },
      { "open_code_replay_mode", null },
      { "show_tamper_diff", null },
      { "show_verification_failure", null },
      { "start_audit_walkthrough", null },
      { "start_experiment_walkthrough", null },
      { "start_code_walkthrough", null },
      { "return_to_workspace", null },
      { "clear_selection", null },
    };
    public static readonly string[] States = { "READY", "QUERYING", "ANSWER RECEIVED", "VALIDATING ACTION", "EXECUTING ACTION", "DONE", "PARTIAL", "FAILED", "UNGROUNDED" };
    public static readonly string[] ExecStatuses = { "EXECUTED", "REJECTED", "TARGET_NOT_FOUND", "UNSUPPORTED_BY_CLIENT", "RENDER_FAILED" };
  }
}
#endif
